version: '3.8'

services:
  todo-app:
    container_name: todo-app-container
    image: almaz91/todo-app-image
    restart: always
    build: ./
    command: ./todo-app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty

  db:
    container_name: getscreen-db
    restart: always
    image: postgres:latest
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5436:5432