version: '3.8'

services:
  db:
    container_name: db
    restart: always
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data

  todo-app:
    container_name: todo-app
    restart: always
    build: 
      context: ./
    env_file:
      - .env
    command: ./todo-app
    ports:
      - 8000:8000
    depends_on:
      - db