version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: qwerty
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
   
  todo-app:
    image: 'almaz91/todo-app:main'
    depends_on:
      - db
    restart: always
    ports:
      - 80:80
    