version: '3.8'

services:
  todo-app:
    restart: always
    build: ./
    command: ./todo-app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty

  db:
    restart: always
    networks:
      - back
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=qwerty
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    